<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Arm parameters -->
  <xacro:property name="arm_base_height" value="0.05"/>
  <xacro:property name="link1_length" value="0.1"/>
  <xacro:property name="link2_length" value="0.15"/>
  <xacro:property name="link3_length" value="0.15"/>
  <xacro:property name="link4_length" value="0.1"/>
  <xacro:property name="link5_length" value="0.05"/>
  <xacro:property name="link6_length" value="0.05"/>
  <xacro:property name="link_radius" value="0.02"/>
  <xacro:property name="joint_radius" value="0.025"/>

  <xacro:macro name="arm" params="parent xyz rpy">
    
    <!-- Arm Base (fixed to robot) -->
    <link name="arm_base_link">
      <visual>
        <geometry>
          <cylinder radius="0.04" length="${arm_base_height}"/>
        </geometry>
        <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
        <material name="arm_dark_grey">
          <color rgba="0.3 0.3 0.3 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.04" length="${arm_base_height}"/>
        </geometry>
        <origin xyz="0 0 ${arm_base_height/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>

    <joint name="arm_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="arm_base_link"/>
      <origin xyz="${xyz}" rpy="${rpy}"/>
    </joint>

    <!-- Joint 1: Base rotation (yaw) -->
    <link name="arm_link_1">
      <visual>
        <geometry>
          <cylinder radius="${joint_radius}" length="${link1_length}"/>
        </geometry>
        <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
        <material name="arm_blue">
          <color rgba="0.2 0.4 0.8 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${joint_radius}" length="${link1_length}"/>
        </geometry>
        <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.3"/>
        <origin xyz="0 0 ${link1_length/2}"/>
        <inertia ixx="0.0005" ixy="0" ixz="0" iyy="0.0005" iyz="0" izz="0.0002"/>
      </inertial>
    </link>

    <joint name="arm_joint_1" type="revolute">
      <parent link="arm_base_link"/>
      <child link="arm_link_1"/>
      <origin xyz="0 0 ${arm_base_height}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14159" upper="3.14159" effort="50" velocity="1.0"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Joint 2: Shoulder pitch -->
    <link name="arm_link_2">
      <visual>
        <geometry>
          <cylinder radius="${link_radius}" length="${link2_length}"/>
        </geometry>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
        <material name="arm_orange">
          <color rgba="0.9 0.5 0.1 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${link_radius}" length="${link2_length}"/>
        </geometry>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.25"/>
        <origin xyz="0 0 ${link2_length/2}"/>
        <inertia ixx="0.0004" ixy="0" ixz="0" iyy="0.0004" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="arm_joint_2" type="revolute">
      <parent link="arm_link_1"/>
      <child link="arm_link_2"/>
      <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="50" velocity="1.0"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Joint 3: Elbow pitch -->
    <link name="arm_link_3">
      <visual>
        <geometry>
          <cylinder radius="${link_radius}" length="${link3_length}"/>
        </geometry>
        <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
        <material name="arm_orange"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${link_radius}" length="${link3_length}"/>
        </geometry>
        <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.2"/>
        <origin xyz="0 0 ${link3_length/2}"/>
        <inertia ixx="0.0003" ixy="0" ixz="0" iyy="0.0003" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="arm_joint_3" type="revolute">
      <parent link="arm_link_2"/>
      <child link="arm_link_3"/>
      <origin xyz="0 0 ${link2_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-2.35" upper="2.35" effort="30" velocity="1.0"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Joint 4: Wrist roll -->
    <link name="arm_link_4">
      <visual>
        <geometry>
          <cylinder radius="${link_radius}" length="${link4_length}"/>
        </geometry>
        <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
        <material name="arm_blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${link_radius}" length="${link4_length}"/>
        </geometry>
        <origin xyz="0 0 ${link4_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.15"/>
        <origin xyz="0 0 ${link4_length/2}"/>
        <inertia ixx="0.0002" ixy="0" ixz="0" iyy="0.0002" iyz="0" izz="0.00005"/>
      </inertial>
    </link>

    <joint name="arm_joint_4" type="revolute">
      <parent link="arm_link_3"/>
      <child link="arm_link_4"/>
      <origin xyz="0 0 ${link3_length}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14159" upper="3.14159" effort="20" velocity="1.5"/>
      <dynamics damping="0.05" friction="0.05"/>
    </joint>

    <!-- Joint 5: Wrist pitch -->
    <link name="arm_link_5">
      <visual>
        <geometry>
          <cylinder radius="${link_radius * 0.8}" length="${link5_length}"/>
        </geometry>
        <origin xyz="0 0 ${link5_length/2}" rpy="0 0 0"/>
        <material name="arm_orange"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${link_radius * 0.8}" length="${link5_length}"/>
        </geometry>
        <origin xyz="0 0 ${link5_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <origin xyz="0 0 ${link5_length/2}"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.00003"/>
      </inertial>
    </link>

    <joint name="arm_joint_5" type="revolute">
      <parent link="arm_link_4"/>
      <child link="arm_link_5"/>
      <origin xyz="0 0 ${link4_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="-1.57" upper="1.57" effort="10" velocity="1.5"/>
      <dynamics damping="0.05" friction="0.05"/>
    </joint>

    <!-- Joint 6: Wrist roll (end effector rotation) -->
    <link name="arm_link_6">
      <visual>
        <geometry>
          <cylinder radius="${link_radius * 0.6}" length="${link6_length}"/>
        </geometry>
        <origin xyz="0 0 ${link6_length/2}" rpy="0 0 0"/>
        <material name="arm_blue"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="${link_radius * 0.6}" length="${link6_length}"/>
        </geometry>
        <origin xyz="0 0 ${link6_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.05"/>
        <origin xyz="0 0 ${link6_length/2}"/>
        <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00002"/>
      </inertial>
    </link>

    <joint name="arm_joint_6" type="revolute">
      <parent link="arm_link_5"/>
      <child link="arm_link_6"/>
      <origin xyz="0 0 ${link5_length}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <limit lower="-3.14159" upper="3.14159" effort="5" velocity="2.0"/>
      <dynamics damping="0.02" friction="0.02"/>
    </joint>

    <!-- End Effector Link (tool frame) -->
    <link name="end_effector_link">
      <visual>
        <geometry>
          <sphere radius="0.01"/>
        </geometry>
        <material name="arm_red">
          <color rgba="1 0 0 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="0.01"/>
        <inertia ixx="0.000001" ixy="0" ixz="0" iyy="0.000001" iyz="0" izz="0.000001"/>
      </inertial>
    </link>

    <joint name="end_effector_joint" type="fixed">
      <parent link="arm_link_6"/>
      <child link="end_effector_link"/>
      <origin xyz="0 0 ${link6_length}" rpy="0 0 0"/>
    </joint>

  </xacro:macro>
</robot>
