<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="gripper_base_length" value="0.03"/>
  <xacro:property name="finger_length" value="0.06"/>
  <xacro:property name="finger_width" value="0.01"/>
  <xacro:property name="finger_height" value="0.02"/>

  <xacro:macro name="gripper" params="parent">

    <!-- Gripper Base -->
    <link name="gripper_base_link">
      <visual>
        <geometry>
          <box size="0.04 0.06 ${gripper_base_length}"/>
        </geometry>
        <origin xyz="0 0 ${gripper_base_length/2}" rpy="0 0 0"/>
        <material name="gripper_grey">
          <color rgba="0.5 0.5 0.5 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="0.04 0.06 ${gripper_base_length}"/>
        </geometry>
        <origin xyz="0 0 ${gripper_base_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.00005" ixy="0" ixz="0" iyy="0.00005" iyz="0" izz="0.00003"/>
      </inertial>
    </link>

    <joint name="gripper_base_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="gripper_base_link"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <!-- Left Finger -->
    <link name="gripper_left_finger">
      <visual>
        <geometry>
          <box size="${finger_width} ${finger_height} ${finger_length}"/>
        </geometry>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <material name="gripper_dark">
          <color rgba="0.2 0.2 0.2 1"/>
        </material>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_width} ${finger_height} ${finger_length}"/>
        </geometry>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.02"/>
        <inertia ixx="0.000005" ixy="0" ixz="0" iyy="0.000005" iyz="0" izz="0.000002"/>
      </inertial>
    </link>

    <joint name="gripper_left_joint" type="prismatic">
      <parent link="gripper_base_link"/>
      <child link="gripper_left_finger"/>
      <origin xyz="0 0.02 ${gripper_base_length}" rpy="0 0 0"/>
      <axis xyz="0 1 0"/>
      <limit lower="0" upper="0.03" effort="10" velocity="0.1"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

    <!-- Right Finger -->
    <link name="gripper_right_finger">
      <visual>
        <geometry>
          <box size="${finger_width} ${finger_height} ${finger_length}"/>
        </geometry>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
        <material name="gripper_dark"/>
      </visual>
      <collision>
        <geometry>
          <box size="${finger_width} ${finger_height} ${finger_length}"/>
        </geometry>
        <origin xyz="0 0 ${finger_length/2}" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="0.02"/>
        <inertia ixx="0.000005" ixy="0" ixz="0" iyy="0.000005" iyz="0" izz="0.000002"/>
      </inertial>
    </link>

    <joint name="gripper_right_joint" type="prismatic">
      <parent link="gripper_base_link"/>
      <child link="gripper_right_finger"/>
      <origin xyz="0 -0.02 ${gripper_base_length}" rpy="0 0 0"/>
      <axis xyz="0 -1 0"/>
      <limit lower="0" upper="0.03" effort="10" velocity="0.1"/>
      <mimic joint="gripper_left_joint" multiplier="1"/>
      <dynamics damping="0.1" friction="0.1"/>
    </joint>

  </xacro:macro>
</robot>
